Repository omigroup/omigroup, pull requests merged in 2022-08, with the labels that each got.

#264 proposed updates and readme.md cleanup pass
  README.md
Labels: Make the metaverse more human, Maintain sustainable innovation

#271 Update README.md
  README.md
Labels: meta

#283 Update WORKING-GROUP-MIN-REQUIREMENTS.md
  WORKING-GROUP-MIN-REQUIREMENTS.md
Labels: Empower the people making the metaverse, Cultivate Resiliency
